
POST {{host}}/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Lorem impsum 8",
  "author": "John Doe",
  "url": "https://example.com/lorem-ipsum-8",
  "likes": 1
}